rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "purchase_notifications"

logging:
  level: "DEBUG"
  format: '%(levelname) -10s %(asctime)s %(module) -30s %(funcName) -35s %(lineno) -5d: %(message)s'

redis:
  host: "localhost"
  port: 6379
  ttl: 300

kafka_producer:
  bootstrap.servers: 'localhost:9092'
  client.id: 'efrat_producer_app'
  acks: 'all'
  retries: 1
  delivery.timeout.ms: 5000
  request.timeout.ms: 4000
  security.protocol: "PLAINTEXT"

kafka_consumer:
  bootstrap.servers: 'localhost:9092'
  group.id: 'hot_products_calculator_group'
  auto.offset.reset: 'earliest'
  enable.auto.commit: 'false'
  security.protocol: "PLAINTEXT"


